name: My First Workflow

on: push

jobs:
  first_job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          #Hash-pinning for your OSS dependencies to protect against repojacking and imposter commits.
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        - name: list and read files
          run: |
            echo "hello world"
            ls
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "dracarys" 

