name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_jobs:
    runs-on: ubuntu:latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        - name: Executing script
          run: ./generate_ascii.sh
